version: '3.1'
services:
  #Nextjs APP
  react-app:
    image: react-app
    build: ./client/
    stdin_open: true
    ports: 
      - "3000:3000"
    volumes: 
      - ./client:/app
      - /app/node_modules
    environment: 
      - CHOKIDAR_USEPOLLING=true
    restart: always
    command: npm run dev
  #API Service
  api-server:
    image: api-servers
    build: ./server/
    ports: 
      - "8000:8000"
    volumes: 
      - ./server:/app
      - /app/node_modules
    environment: 
      - CHOKIDAR_USEPOLLING=true
    restart: always
    command: npm run dev
  #mongo db database
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
  # Mongo Express DB Ui
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
