version: '3'
services: 
  react-app:
    image: react-apps
    build: ./client/
    stdin_open: true
    ports: 
      - "3000:3000"
    networks: 
      - mern-app
    volumes: 
      - ./client/:/app/
    environment: 
      - CHOKIDAR_USEPOLLING=true
  api-server:
    image: api-servers
    build: ./server/
    ports: 
      - "8000:8000"
    networks: 
      - mern-app
    volumes: 
      - ./server/:/app/
    environment: 
      - CHOKIDAR_USEPOLLING=true
networks: 
  mern-app:
    driver: bridge


